version: '3'

networks:
  mlc_net:
    external:
      name: mlc_net

services:
  gi:
    build: .
    container_name: gi
    volumes:
      - ./src/gi:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8002:8000
    environment:
      - API_PUBLIC_URL=http://localhost:8000
      - API_INTERNAL_URL=http://api:8000
      - DJANGO_DEBUG=True
      - TEST=False
    networks:
      - mlc_net
